---
- name: Variables Example
  hosts: all
  become: yes
  
  vars:
    package_name: nginx
    service_name: nginx
    service_port: 80
  
  tasks:
  - name: Install Nginx from Variables
    yum:
      name: "{{ package_name }}"
      state: present
 
  - name: Start Nginx service from variables  
    service:
      name: "{{ service_name }}"
      state: started
  
  - name: Display service information from variables
    debug:
      msg: "Running {{ service_name }} on port {{ service_port }}"
