---
- name: Install Package
  hosts: all
  become: yes
  
  tasks: 
  - name: Install nginx package
    yum:
      name: nginx
      state: present
  
  - name: Start nginx Service
    service:
      name: nginx
      state: started
      enabled: yes
