apiVersion: v1
kind: Pod

metadata:
  name: nginx

spec:
  containers:
  - name: nginx-container
    image: nginx
=================================================================================
Multi-Container Yaml 


apiVersion: v1
kind: Pod
metadata:
  name: my-pod1
spec:
  containers:
    - name: container1
      image: nginx
    - name: container2
      image: nginx

How to run yaml file

>>> sudo kubectl apply -f myfile.yaml
==========================================================================================
>>>>>>>>>>>>>>>>>>>>Deployment Manifest<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-demo

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx-demo

  template:
    metadata:
      labels:
        app: nginx-demo

    spec:
      containers:
      - name: nginx
        image: nginx:1.24

=========================================================================================================
>>>>>>>>>>>>>>>>>>>>>> AUTOSCALING YAML<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: cpu-demo1
  name: cpu-demo1

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cpu-demo1

  template:
    metadata:
      labels:
        app: cpu-demo1

    spec:
      containers:
        - image: busybox
          name: busybox

          command:
            - /bin/sh
            - -c

          args:
            - while true; do :; done

          resources:
            requests:
              cpu: 100m

            limits:
              cpu: 200m

==========================================================================================
>>>>>>>>>>>>>>>>>>>>>>>>>>NodePort Service<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

apiVersion: v1
kind: Service
metadata:
  name: my-svc

spec:
  selector:
    app: my-app

  type: NodePort

  ports:
  - port: 80
    targetPort: 80
    nodePort: 32008
=============================================================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myconfig-deploy
  namespace: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mykube
        image: nginx

        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-config

-----------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Pod

metadata:
  name: nginx-secret
  labels:
    app: nginx

spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret

  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret
====================================================================================================================

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Persistent Volume<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

apiVersion: v1                  # Core Kubernetes API
kind: PersistentVolume          # We are creating a PV

metadata:
  name: nginx-pv                # Name of the PV

spec:

  capacity:
    storage: 1Gi                # Total storage available

  accessModes:
  - ReadWriteOnce               # One node can read/write

  persistentVolumeReclaimPolicy: Retain
                                # Keep data even if PVC is deleted

  hostPath:
    path: /data/nginx           # Actual storage on host machine
-----------------------------------------------------------------------------------------------
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Persistent Vloume Claim<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

apiVersion: v1                    # Core Kubernetes API
kind: PersistentVolumeClaim       # We are creating a PVC

metadata:
  name: nginx-pvc                 # Name of PVC

spec:
  storageClassName: ""        # Disable dynamic provisioning
  volumeClaim: nginx-pv

  accessModes:
  - ReadWriteOnce                 # Must match PV access mode

  resources:
    requests:
      storage: 500Mi              # Request 500MB storage
-------------------------------------------------------------------------------------------------
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Deployment with PVC<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

apiVersion: apps/v1                 # Which Kubernetes API handles Deployment
kind: Deployment                    # Create a Deployment object

metadata:
  name: nginx-pv-deploy             # Name of the Deployment

spec:

  replicas: 2                       # Number of Pods required

  selector:                         # How Deployment identifies its Pods
    matchLabels:
      app: nginx                    # Look for Pods with label app=nginx

  template:                         # Blueprint/template for creating Pods

    metadata:
      labels:
        app: nginx                  # Label assigned to Pods

    spec:

      containers:                   # Container definitions start here

      - name: nginx                 # Container name
        image: nginx                # Docker image to run

        ports:
        - containerPort: 80         # Application listens on port 80

        volumeMounts:               # Mount storage inside container
        - name: website-storage     # Volume name (must match below)
          mountPath: /usr/share/nginx/html
                                   # Location inside container where storage is attached

      volumes:                      # Define storage for the Pod
      - name: website-storage       # Volume name referenced above

        persistentVolumeClaim:      # Use storage provided by a PVC
          claimName: nginx-pvc      # Name of existing PVC
